#!/bin/bash

#PORT=8888
#LOCAL='127.0.0.1:'PORT
#ANY='0.0.0.0:8080:'PORT

#todo local host only or 0.0.0.0:8080

#echo 'to switch off launching of browser or to use any other browser than the default - edit this file'

cd www

php -S 127.0.0.1:8888 #$LOCAL

cd ..

#launch web browser
#uname -a | grep Darwin