<?php

echo $data;

?>

<!-- Tabs -->
		<h2 class="demoHeaders">Tabs</h2>
		<div id="tabs">
			<ul>
				<li><a href="#tabs-1">First</a></li>
				<li><a href="#tabs-2">Second</a></li>
				<li><a href="#tabs-3">Third</a></li>
			</ul>
			<div id="tabs-1">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</div>
			<div id="tabs-2">Phasellus mattis tincidunt nibh. Cras orci urna, blandit id, pretium vel, aliquet ornare, felis. Maecenas scelerisque sem non nisl. Fusce sed lorem in enim dictum bibendum.</div>
			<div id="tabs-3">Nam dui erat, auctor a, dignissim quis, sollicitudin eu, felis. Pellentesque nisi
			erferf
			rewg
			wrg
			wreg
			rwt
			h
			etyh
			wt
			yhj
			tyw
			h
			wtyh
			urna, interdum eget, sagittis et, consequat vestibulum, lacus. Mauris porttitor ullamcorper augue.</div>
		</div>

<!-- Dialog NOTE: Dialog is not generated by UI in this demo so it can be visually styled in themeroller-->
		<h2 class="demoHeaders">Dialog</h2>
		<p><a href="#" id="dialog_link" class="ui-state-default ui-corner-all"  onclick="shh('osUpdate')"><span class="ui-icon ui-icon-newwin"></span>sh</a></p>

<!-- ui-dialog -->
		<div id="dialog" title="Dialog Title">
			Lorem
		</div>

<input
	type="button" value="test ajax sh" onclick="sh('test','')" />

	<input type="button" value="shell" onclick="aajax('/system/index/shell','shell')" />
<div id="shell"></div>
<input
	type="button" value="OS Update" onclick="shh('osUpdate','')" />

<div class="ui-widget">
	<div class="ui-state-highlight ui-corner-all"
		style="margin-top: 20px; padding: 0 .7em;">
		<p>
			<span class="ui-icon ui-icon-info"
				style="float: left; margin-right: .3em;"></span> <strong>EXECUTING</strong>
			' . $cmd . '
		</p>
	</div>
</div>


<div class="ui-widget">
	<div class="ui-state-error ui-corner-all" style="padding: 0 .7em;">
		<p>
			<span class="ui-icon ui-icon-alert"
				style="float: left; margin-right: .3em;"></span> <strong>Alert:</strong>
			Sample ui-state-error style.
		</p>
	</div>
</div>

<div id="sh"></div>
<div id="status"></div>
